/* ==========================================================================
   ✿ 中文 Studio Vocabulary Database (words.js)
   Created by astagme
   Full HSK 1 (Band 1) Vocabulary Set
   ========================================================================== */

const allWords = [
  // ==================== 1. PRONOUNS & QUESTIONS (Местоимения и вопросительные слова) ====================
  { hanzi: "我", pinyin: "wǒ", meaning: "я (I, me)", cat: "Pronoun", hsk: 1, radicals: "手 (рука) + 戈 (оружие)", story: "Рука с оружием защищает 'самого себя'." },
  { hanzi: "你", pinyin: "nǐ", meaning: "ты (you)", cat: "Pronoun", hsk: 1, radicals: "亻(человек) + 尔 (малый)", story: "Человек, стоящий прямо перед тобой." },
  { hanzi: "他", pinyin: "tā", meaning: "он (he, him)", cat: "Pronoun", hsk: 1, radicals: "亻(человек) + 也 (тоже)", story: "Еще один человек (мужчина) в стороне." },
  { hanzi: "她", pinyin: "tā", meaning: "она (she, her)", cat: "Pronoun", hsk: 1, radicals: "女 (женщина) + 也 (тоже)", story: "Человек женского пола." },
  { hanzi: "它", pinyin: "tā", meaning: "оно (it)", cat: "Pronoun", hsk: 1, radicals: "宀 (крыша) + 匕", story: "Предмет или животное под крышей." },
  { hanzi: "我们", pinyin: "wǒmen", meaning: "мы (we, us)", cat: "Pronoun", hsk: 1, radicals: "我 + 门 (множественность)", story: "Несколько человек, включая меня." },
  { hanzi: "你们", pinyin: "nǐmen", meaning: "вы (you all)", cat: "Pronoun", hsk: 1, radicals: "你 + 门 (множественность)", story: "Группа людей, к которым ты обращаешься." },
  { hanzi: "他们", pinyin: "tāmen", meaning: "они (they - муж./смеш.)", cat: "Pronoun", hsk: 1, radicals: "他 + 门", story: "Группа людей за пределами разговора." },
  { hanzi: "她们", pinyin: "tāmen", meaning: "они (they - жен.)", cat: "Pronoun", hsk: 1, radicals: "她 + 门", story: "Группа девушек или женщин." },
  { hanzi: "这", pinyin: "zhè", meaning: "это, этот (this)", cat: "Pronoun", hsk: 1, radicals: "辶 (движение) + 文", story: "Указывает на что-то близкое, прямо здесь." },
  { hanzi: "那", pinyin: "nà", meaning: "то, тот (that)", cat: "Pronoun", hsk: 1, radicals: "阝(город/место) + 𠄎", story: "Указывает на предмет вдали." },
  { hanzi: "哪", pinyin: "nǎ", meaning: "какой, который (which)", cat: "Pronoun", hsk: 1, radicals: "口 (рот) + 那", story: "Вопрос ртом: 'который именно?'" },
  { hanzi: "谁", pinyin: "shuí", meaning: "кто (who)", cat: "Pronoun", hsk: 1, radicals: "讠(речь) + 隹 (птица)", story: "Спрашиваем голосом, кто же это." },
  { hanzi: "什么", pinyin: "shénme", meaning: "что, какой (what)", cat: "Pronoun", hsk: 1, radicals: "亻(человек) + 十", story: "Вопрос о неизвестной вещи." },
  { hanzi: "多少", pinyin: "duōshao", meaning: "сколько (>10) (how much)", cat: "Pronoun", hsk: 1, radicals: "多 (много) + 少 (мало)", story: "Узнаем объем: много или мало?" },
  { hanzi: "几", pinyin: "jǐ", meaning: "сколько (<10), несколько", cat: "Pronoun", hsk: 1, radicals: "几 (столик)", story: "Подсчет небольшого количества." },
  { hanzi: "怎么", pinyin: "zěnme", meaning: "как, каким образом (how)", cat: "Pronoun", hsk: 1, radicals: "心 (сердце) + 乍", story: "Спрашиваем о способе действия." },
  { hanzi: "怎么样", pinyin: "zěnmeyàng", meaning: "как насчет, каков? (how about)", cat: "Pronoun", hsk: 1, radicals: "怎么 + 样 (вид)", story: "Интересуемся мнением или состоянием." },

  // ==================== 2. NUMBERS (Числительные) ====================
  { hanzi: "一", pinyin: "yī", meaning: "один (1)", cat: "Number", hsk: 1, radicals: "一 (единица)", story: "Одна горизонтальная черта." },
  { hanzi: "二", pinyin: "èr", meaning: "два (2)", cat: "Number", hsk: 1, radicals: "二 (двойка)", story: "Две параллельные черты." },
  { hanzi: "三", pinyin: "sān", meaning: "три (3)", cat: "Number", hsk: 1, radicals: "三 (тройка)", story: "Три параллельные черты." },
  { hanzi: "四", pinyin: "sì", meaning: "четыре (4)", cat: "Number", hsk: 1, radicals: "囗 (ограда) + 儿", story: "Окошко, разделенное на 4 части." },
  { hanzi: "五", pinyin: "wǔ", meaning: "пять (5)", cat: "Number", hsk: 1, radicals: "二 + 乂", story: "Перекрещенные линии число 5." },
  { hanzi: "六", pinyin: "liù", meaning: "шесть (6)", cat: "Number", hsk: 1, radicals: "亠 + 八", story: "Цифра 6." },
  { hanzi: "七", pinyin: "qī", meaning: "семь (7)", cat: "Number", hsk: 1, radicals: "一 + 乚", story: "Перевернутая семерка." },
  { hanzi: "八", pinyin: "bā", meaning: "восемь (8)", cat: "Number", hsk: 1, radicals: "八 (разделение)", story: "Две раскрывающиеся черты." },
  { hanzi: "九", pinyin: "jiǔ", meaning: "девять (9)", cat: "Number", hsk: 1, radicals: "乙", story: "Цифра 9." },
  { hanzi: "十", pinyin: "shí", meaning: "десять (10)", cat: "Number", hsk: 1, radicals: "十 (крест)", story: "Крест, обозначающий десяток." },
  { hanzi: "百", pinyin: "bǎi", meaning: "соточку, сто (100)", cat: "Number", hsk: 1, radicals: "白 (белый) + 一", story: "Число сто." },
  { hanzi: "零", pinyin: "líng", meaning: "ноль (0)", cat: "Number", hsk: 1, radicals: "雨 (дождь) + 令", story: "Капельки ноля." },

  // ==================== 3. FAMILY & PEOPLE (Семья и люди) ====================
  { hanzi: "妈妈", pinyin: "māma", meaning: "мама (mom)", cat: "Noun", hsk: 1, radicals: "女 (женщина) + 马 (лошадь)", story: "Женщина, которая трудится ради семьи как лошадка." },
  { hanzi: "爸爸", pinyin: "bàba", meaning: "папа (dad)", cat: "Noun", hsk: 1, radicals: "父 (отец) + 巴", story: "Глава семейства." },
  { hanzi: "儿子", pinyin: "érzi", meaning: "сын (son)", cat: "Noun", hsk: 1, radicals: "儿 (ребенок) + 子", story: "Маленький мальчик в семье." },
  { hanzi: "女儿", pinyin: "nǚ'ér", meaning: "дочь (daughter)", cat: "Noun", hsk: 1, radicals: "女 (женщина) + 儿", story: "Девочка-ребенок." },
  { hanzi: "老师", pinyin: "lǎoshī", meaning: "учитель (teacher)", cat: "Noun", hsk: 1, radicals: "老 (старый/мудрый) + 师 (мастер)", story: "Опытный наставник." },
  { hanzi: "学生", pinyin: "xuésheng", meaning: "ученик, студент (student)", cat: "Noun", hsk: 1, radicals: "学 (учиться) + 生 (рождаться)", story: "Человек, растущий через учебу." },
  { hanzi: "同学", pinyin: "tóngxué", meaning: "одноклассник (classmate)", cat: "Noun", hsk: 1, radicals: "同 (вместе) + 学 (учеба)", story: "Тот, кто учится вместе с тобой." },
  { hanzi: "朋友", pinyin: "péngyou", meaning: "друг (friend)", cat: "Noun", hsk: 1, radicals: "月 (луна) + 友 (друг)", story: "Две луны рядом — символизируют дружбу." },
  { hanzi: "医生", pinyin: "yīshēng", meaning: "врач, доктор (doctor)", cat: "Noun", hsk: 1, radicals: "医 (лечить) + 生", story: "Человек, который дарует здоровье." },
  { hanzi: "先生", pinyin: "xiānsheng", meaning: "господин, муж (Mr.)", cat: "Noun", hsk: 1, radicals: "先 (прежде) + 生", story: "Уважительное обращение к мужчине." },

  // ==================== 4. KEY VERBS (Основные глаголы) ====================
  { hanzi: "是", pinyin: "shì", meaning: "быть, являться (to be)", cat: "Verb", hsk: 1, radicals: "日 (солнце) + 疋", story: "Солнце светит прямо — это истина и факт." },
  { hanzi: "有", pinyin: "yǒu", meaning: "иметь, обладать (have)", cat: "Verb", hsk: 1, radicals: "𠂇 (рука) + 月 (мясо)", story: "Держать кусок мяса в руке — значит иметь еду." },
  { hanzi: "看", pinyin: "kàn", meaning: "смотреть, читать (watch/read)", cat: "Verb", hsk: 1, radicals: "手 (рука) + 目 (глаз)", story: "Приложить руку к глазам и вглядываться вдаль." },
  { hanzi: "听", pinyin: "tīng", meaning: "слушать (listen)", cat: "Verb", hsk: 1, radicals: "口 (рот) + 斤 (топор)", story: "Вслушиваться ротиком в звуки вокруг." },
  { hanzi: "说", pinyin: "shuō", meaning: "говорить, сказать (speak)", cat: "Verb", hsk: 1, radicals: "讠(речь) + 兑", story: "Произносить слова вслух." },
  { hanzi: "读", pinyin: "dú", meaning: "читать вслух (read out)", cat: "Verb", hsk: 1, radicals: "讠(речь) + 卖", story: "Произносить слова по книге." },
  { hanzi: "写", pinyin: "xiě", meaning: "писать (write)", cat: "Verb", hsk: 1, radicals: "冖 (крыша) + 与", story: "Аккуратно выводить иероглифы дома." },
  { hanzi: "吃", pinyin: "chī", meaning: "есть, кушать (eat)", cat: "Verb", hsk: 1, radicals: "口 (рот) + 乞", story: "Класть вкусную еду в рот." },
  { hanzi: "喝", pinyin: "hē", meaning: "пить (drink)", cat: "Verb", hsk: 1, radicals: "口 (рот) + 曷", story: "Пить напиток ртом." },
  { hanzi: "去", pinyin: "qù", meaning: "идти, уходить (go)", cat: "Verb", hsk: 1, radicals: "土 (земля) + 厶", story: "Уходить прочь по земле." },
  { hanzi: "来", pinyin: "lái", meaning: "приходить, приезжать (come)", cat: "Verb", hsk: 1, radicals: "木 (дерево) + 🌾", story: "Приходить к месту назначения." },
  { hanzi: "做", pinyin: "zuò", meaning: "делать, готовить (do/make)", cat: "Verb", hsk: 1, radicals: "亻(человек) + 故", story: "Человек за работой." },
  { hanzi: "坐", pinyin: "zuò", meaning: "сидеть, ехать на (sit)", cat: "Verb", hsk: 1, radicals: "人+人+土 (земля)", story: "Два человека сидят на земле." },
  { hanzi: "买", pinyin: "mǎi", meaning: "покупать (buy)", cat: "Verb", hsk: 1, radicals: "乛 + 头", story: "Отдавать деньги за покупку." },
  { hanzi: "开", pinyin: "kāi", meaning: "открывать, водить (open/drive)", cat: "Verb", hsk: 1, radicals: "开 (ворота)", story: "Распахивать двери или водить авто." },
  { hanzi: "爱", pinyin: "ài", meaning: "любить (love)", cat: "Verb", hsk: 1, radicals: "爪 (лапа) + 友 (друг)", story: "Протягивать руки с любовью и обнимать." },
  { hanzi: "喜欢", pinyin: "xǐhuan", meaning: "нравиться (like)", cat: "Verb", hsk: 1, radicals: "吉 (радость) + 欠", story: "Испытывать симпатию." },
  { hanzi: "想", pinyin: "xiǎng", meaning: "хотеть, скучать, думать (want/think)", cat: "Verb", hsk: 1, radicals: "相 + 心 (сердце)", story: "Держать образ человека в сердце." },
  { hanzi: "能", pinyin: "néng", meaning: "мочь, быть в состоянии (can)", cat: "Verb", hsk: 1, radicals: "厶 + 月 + 匕", story: "Сила и физическая возможность." },
  { hanzi: "会", pinyin: "huì", meaning: "уметь, владеть навыком (know how)", cat: "Verb", hsk: 1, radicals: "人 (человек) + 云 (облако)", story: "Навык, которому научился человек." },

  // ==================== 5. DAILY OBJECTS & PLACES (Предметы и места) ====================
  { hanzi: "家", pinyin: "jiā", meaning: "дом, семья (home/family)", cat: "Noun", hsk: 1, radicals: "宀 (крыша) + 豕 (свинья)", story: "Дом с крышей и хозяйством." },
  { hanzi: "学校", pinyin: "xuéxiào", meaning: "школа (school)", cat: "Noun", hsk: 1, radicals: "学 (учиться) + 校 (здание)", story: "Место обучения детей." },
  { hanzi: "饭店", pinyin: "fàndiàn", meaning: "ресторан (restaurant)", cat: "Noun", hsk: 1, radicals: "饭 (еда) + 店 (магазин)", story: "Заведение, где подают еду." },
  { hanzi: "商店", pinyin: "shāngdiàn", meaning: "магазин (shop)", cat: "Noun", hsk: 1, radicals: "商 (торговля) + 店", story: "Место торговли товарами." },
  { hanzi: "医院", pinyin: "yīyuàn", meaning: "больница (hospital)", cat: "Noun", hsk: 1, radicals: "医 (лечить) + 院 (двор)", story: "Здание медпомощи." },
  { hanzi: "中国", pinyin: "Zhōngguó", meaning: "Китай (China)", cat: "Noun", hsk: 1, radicals: "中 (середина) + 国 (государство)", story: "Срединное государство." },
  { hanzi: "北京", pinyin: "Běijīng", meaning: "Пекин (Beijing)", cat: "Noun", hsk: 1, radicals: "北 (север) + 京 (столица)", story: "Северная столица." },
  { hanzi: "书", pinyin: "shū", meaning: "книга (book)", cat: "Noun", hsk: 1, radicals: "乛 + 亅", story: "Переплетенные страницы мудрости." },
  { hanzi: "水", pinyin: "shuǐ", meaning: "вода (water)", cat: "Noun", hsk: 1, radicals: "水 (вода)", story: "Текущий речной поток." },
  { hanzi: "茶", pinyin: "chá", meaning: "чай (tea)", cat: "Noun", hsk: 1, radicals: "艹 (трава) + 木 (дерево)", story: "Листочки с чайного куста." },
  { hanzi: "米饭", pinyin: "mǐfàn", meaning: "вареный рис (rice)", cat: "Noun", hsk: 1, radicals: "米 (рис) + 饭 (еда)", story: "Главный гарнир." },
  { hanzi: "苹果", pinyin: "píngguǒ", meaning: "яблоко (apple)", cat: "Noun", hsk: 1, radicals: "艹 + 果 (фрукт)", story: "Сочный фрукт." },
  { hanzi: "猫", pinyin: "māo", meaning: "кошка (cat)", cat: "Noun", hsk: 1, radicals: "犭(зверь) + 苗 (побег)", story: "Пушистый зверек." },
  { hanzi: "狗", pinyin: "gǒu", meaning: "собака (dog)", cat: "Noun", hsk: 1, radicals: "犭(зверь) + 句", story: "Верный пес у дома." },
  { hanzi: "钱", pinyin: "qián", meaning: "деньги (money)", cat: "Noun", hsk: 1, radicals: "钅(металл) + 戋", story: "Монеты для оплаты." },
  { hanzi: "飞机", pinyin: "fēijī", meaning: "самолет (airplane)", cat: "Noun", hsk: 1, radicals: "飞 (летать) + 机 (машина)", story: "Летающий аппарат." },
  { hanzi: "出租车", pinyin: "chūzūchē", meaning: "такси (taxi)", cat: "Noun", hsk: 1, radicals: "出 (выезд) + 租 + 车 (машина)", story: "Машина в аренду." },
  { hanzi: "电脑", pinyin: "diànnǎo", meaning: "компьютер (computer)", cat: "Noun", hsk: 1, radicals: "电 (электричество) + 脑 (мозг)", story: "Электронный мозг." },
  { hanzi: "电视", pinyin: "diànshì", meaning: "телевизор (TV)", cat: "Noun", hsk: 1, radicals: "电 + 视 (зрение)", story: "Электрический экран." },

  // ==================== 6. TIME & DATES (Время и даты) ====================
  { hanzi: "今天", pinyin: "jīntiān", meaning: "сегодня (today)", cat: "Time", hsk: 1, radicals: "今 (сейчас) + 天 (день)", story: "Текущий день." },
  { hanzi: "明天", pinyin: "míngtiān", meaning: "завтра (tomorrow)", cat: "Time", hsk: 1, radicals: "明 (светлый: 日+月) + 天", story: "Светлый следующий день." },
  { hanzi: "昨天", pinyin: "zuótiān", meaning: "вчера (yesterday)", cat: "Time", hsk: 1, radicals: "日 (солнце) + 乍 + 天", story: "Прошедший день." },
  { hanzi: "年", pinyin: "nián", meaning: "год (year)", cat: "Time", hsk: 1, radicals: "干 + 𠂉", story: "Годовой цикл урожая." },
  { hanzi: "月", pinyin: "yuè", meaning: "месяц, луна (month)", cat: "Time", hsk: 1, radicals: "月 (луна)", story: "Месячный лунный календарь." },
  { hanzi: "日", pinyin: "rì", meaning: "день, число, солнце (day)", cat: "Time", hsk: 1, radicals: "日 (солнце)", story: "Солнечный день." },
  { hanzi: "星期", pinyin: "xīngqī", meaning: "неделя (week)", cat: "Time", hsk: 1, radicals: "日 + 其", story: "Дни недели." },
  { hanzi: "点", pinyin: "diǎn", meaning: "час (о времени) (o'clock)", cat: "Time", hsk: 1, radicals: "占 + 灬 (точки)", story: "Отметка времени на часах." },
  { hanzi: "分钟", pinyin: "fēnzhōng", meaning: "минута (minute)", cat: "Time", hsk: 1, radicals: "分 (деление) + 钟 (часы)", story: "Минутные отрезки времени." },

  // ==================== 7. ADJECTIVES & PARTICLES (Прилагательные и частицы) ====================
  { hanzi: "好", pinyin: "hǎo", meaning: "хороший (good)", cat: "Adjective", hsk: 1, radicals: "女 (женщина) + 子 (ребенок)", story: "Мама с ребенком — символ гармонии." },
  { hanzi: "大", pinyin: "dà", meaning: "большой (big)", cat: "Adjective", hsk: 1, radicals: "大 (человек с расставленными руками)", story: "Человек развел руки широко." },
  { hanzi: "小", pinyin: "xiǎo", meaning: "маленький (small)", cat: "Adjective", hsk: 1, radicals: "小 (маленький)", story: "Крошечные капельки." },
  { hanzi: "多", pinyin: "duō", meaning: "много (many)", cat: "Adjective", hsk: 1, radicals: "夕 (вечер) + 夕", story: "Две луны ночи — много времени." },
  { hanzi: "少", pinyin: "shǎo", meaning: "мало (few)", cat: "Adjective", hsk: 1, radicals: "小 + ノ", story: "Совсем немного." },
  { hanzi: "冷", pinyin: "lěng", meaning: "холодный (cold)", cat: "Adjective", hsk: 1, radicals: "冫(лед) + 令", story: "Ледяной мороз." },
  { hanzi: "热", pinyin: "rè", meaning: "горячий, жаркий (hot)", cat: "Adjective", hsk: 1, radicals: "执 + 灬 (огонь)", story: "Пламя огня и жара." },
  { hanzi: "高兴", pinyin: "gāoxìng", meaning: "радостный (happy)", cat: "Adjective", hsk: 1, radicals: "高 (высокий) + 兴", story: "Высокий подъем духа." },
  { hanzi: "漂亮", pinyin: "piàoliang", meaning: "красивый (pretty)", cat: "Adjective", hsk: 1, radicals: "氵(вода) + 亮 (свет)", story: "Чистый и красивый образ." },
  { hanzi: "不", pinyin: "bù", meaning: "не, нет (not)", cat: "Particle", hsk: 1, radicals: "一 + 丨", story: "Отрицательная частица." },
  { hanzi: "没", pinyin: "méi", meaning: "не иметь, отрицание (not have)", cat: "Particle", hsk: 1, radicals: "氵(вода) + 殳", story: "Отрицание наличия." },
  { hanzi: "很", pinyin: "hěn", meaning: "очень (very)", cat: "Adverb", hsk: 1, radicals: "彳(шаг) + 艮", story: "Усилитель перед прилагательными." },
  { hanzi: "在", pinyin: "zài", meaning: "находиться в/на (at/in)", cat: "Particle", hsk: 1, radicals: "土 (земля)", story: "Указание на местоположение." },
  { hanzi: "的", pinyin: "de", meaning: "притяжательная частица ('s)", cat: "Particle", hsk: 1, radicals: "白 (белый) + 勺", story: "Связывает обладателя и предмет (我的书)." },
  { hanzi: "吗", pinyin: "ma", meaning: "вопросительная частица", cat: "Particle", hsk: 1, radicals: "口 (рот) + 马 (лошадь)", story: "Ставится в конце предложения для вопроса." },
  { hanzi: "呢", pinyin: "ne", meaning: "вопросительная частица 'а...?'", cat: "Particle", hsk: 1, radicals: "口 (рот) + 尼", story: "Обратный вопрос: 'А ты?'" },
  { hanzi: "太", pinyin: "tài", meaning: "слишком (too)", cat: "Adverb", hsk: 1, radicals: "大 + 点", story: "Слишком много (太好了!)." }
];
